version: '3'
services:
  esme_mongodb:
    build:
      context: ./esme_mongodb
    ports:
      - "27017:27017"
    volumes:
      - /data/db 
      - ./esme_mongodb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  
  esme_admin:
    build:
      context: ./esme_admin
    ports:
      - "3000:3000"
    environment:
      - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://esme_mongodb:27017/geography
    volumes:
      - /data/db
  esme_console:
    build:
      context: ./esme_console
    ports:
      - "7681:7681"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
